# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quote',
            name='favorite',
        ),
        migrations.AlterField(
            model_name='quote',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belt_3.User'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='quote_liked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belt_3.Quote'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belt_3.User'),
        ),
    ]
