# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 21:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('belt_3', '0002_auto_20160925_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='quote_liked',
        ),
        migrations.AddField(
            model_name='favorite',
            name='quote_like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_liked', to='belt_3.Quote'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user_like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_liked', to='belt_3.User'),
        ),
    ]
